version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
     - image: circleci/python:2-jessie-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login docker hub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build laravel docker image
          command: docker build -t ${PROPERTY}/web:${CIRCLE_SHA1} .
      - run:
          name: Push to DockerHub account
          command: docker push ${PROPERTY}/web:${CIRCLE_SHA1}
      # - run: ssh -o StrictHostKyeChecking=no root@host.co "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"
