version: 2
jobs:

  developer:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Running Unit Test
          command: yarn test

  staging:
    working_directory: ~/repo
    docker: # run the steps with Docker
      - image: circleci/node:latest-browsers-legacy
    steps:
      # - add_ssh_keys:
      #     fingerprints:
      #       - "54:ba:e5:53:bb:01:e9:d9:31:63:3b:d0:22:4e:6a:7b"
      - checkout
      - setup_remote_docker
      - run:
          name: Login docker hub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build React docker image
          command: docker build -t ${DOCKER_USER}/web:${CIRCLE_SHA1} .
      - run:
          name: Push to DockerHub account
          command: docker push ${DOCKER_USER}/web:${CIRCLE_SHA1}
      # - run: ssh -o StrictHostKyeChecking=no root@host.co "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"
  
  production:
    working_directory: ~/repo
    docker: # run the steps with Docker
      - image: circleci/node:latest-browsers-legacy
    steps:
      # - add_ssh_keys:
      #     fingerprints:
      #       - "54:ba:e5:53:bb:01:e9:d9:31:63:3b:d0:22:4e:6a:7b"
      - checkout
      - setup_remote_docker

workflows:
  version: 2
  ci:
    jobs:
      - developer
  cd:
    jobs:
      - staging:
          requires:
            - developer
          context: development
          filters:
            branches:
              only:
                - development
      - production:
          requires:
            - developer
          context: production
          filters:
            branches:
              only:
                - master