version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
     - image: circleci/python:2-jessie-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Running Unit Test
          command: npm test
      - run:
          name: Login docker hub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build laravel docker image
          command: docker build -t ${DOCKER_USER}/web:${CIRCLE_SHA1} .
      - run:
          name: Push to DockerHub account
          command: docker push ${DOCKER_USER}/web:${CIRCLE_SHA1}
      # - run: ssh -o StrictHostKyeChecking=no root@host.co "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build-job 
#       - deploy-job:
#           requires:
#             - build-job # Only deploy once the build job has completed
#           filters:
#             branches:
#               only: master # Only deploy on the master branch